### ISSUE TITLE
Is this c++ crosswalk plugin methodology valid?

### ISSUE THREAD

**Issue by eahutchins** [MobileChromeApps/mobile-chrome-apps#471]
I recently found this page:

https://github.com/crosswalk-project/crosswalk-website/wiki/Writing-a-Crosswalk-Extension

which seems to show a different native-code extension mechanism with a direct native<->javascript binding.  Is this stale information? Would I have to build my own crosswalk? Is there a good example showing native code glued into cca (including build environment and detailed instructions)? I'm looking for the simplest way to glue some computationally intensive C code into my cca app.

**Comment by jpchase** [comment]
In the long term, the recommendation is to use the system web view, instead of Crosswalk, on Android L+.  See our docs for details: https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/docs/Crosswalk.md.

As result, we're not investigating or supporting Crosswalk extensions at this time.
