### ISSUE TITLE
Blank screen on iOS (cca v0.5.2-dev)

### ISSUE THREAD

**Issue by tanx** [MobileChromeApps/mobile-chrome-apps#497]
I don't know if this related to https://github.com/MobileChromeApps/mobile-chrome-apps/issues/457 but when spinning up Whiteout on the current version of cca, I get blank screen on iOS 8.1.2. I can't debug the issue in Safari because none of my scripts are visible in the remote debugger. What am I doing wrong?

**Comment by felixhammerl** [comment]
we just tracked the issue down to the use of inline svg for icons ([all of those](https://github.com/whiteout-io/mail-html5/tree/master/src/img/icons) concatenated into one) that are [inserted here](https://github.com/whiteout-io/mail-html5/blob/master/src/index.html#L38)

```
<div style="width: 0; height: 0; visibility: hidden;">
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
<symbol viewBox="155.9 279.2 283.5 283.5" id="icon-about"><title>about</title><path ... />
</symbol><symbol viewBox="155.9 279.2 283.5 283.5" id="icon-account"><title>account</title><path ... /></symbol></svg>
</div>
```

if this is in the markup, the dom loading times out after a couple of seconds. 

is there any known problem with this practice? it doesn't seem to be a csp problem, since it still occurs if we [remove this line](https://github.com/whiteout-io/mail-html5/blob/master/src/index.html#L8), or is there a default CSP setting by now?

**Comment by tanx** [comment]
The error was on our side. Sorry for the noise. As you were :+1:

**Comment by agrieve** [comment]
Awe, what a cliff-hanger! Was it something to do with svg in the end? Is there some gotcha to avoid here?

**Comment by felixhammerl** [comment]
when we concatenated the svg, we used was a) the individual sources and b) the concatenated source, so basically we duplicated the svg. that seems to have broken the parser or something along the way. on a semi-related note: does cca use the WKWebView or the (legacy) UIWebView?

**Comment by agrieve** [comment]
Interesting :P.

It uses UIWebView. We'll be onboard with wkwebview though once Cordova
supports it.
