### ISSUE TITLE
Addding PushPlugin breaks android build

### ISSUE THREAD

**Issue by uriva** [MobileChromeApps/mobile-chrome-apps#509]
Trying to add this plugin:
cordova plugin add https://github.com/phonegap-build/PushPlugin.git

Then
cca run android

Getting this error during the build:

UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

**Comment by mmocny** [comment]
Looks like they include the [android-support-v13 library](https://github.com/phonegap-build/PushPlugin/blob/master/plugin.xml#L66) right inline in their push plugin.  They also use the [gcm helper libraries](https://developer.android.com/google/gcm/helper.html) which are apparently deprecated.

We use [android-support-v4](https://github.com/MobileChromeApps/cordova-plugin-android-support-v4) which is referenced from several of our plugins, and I believe [includes the accessibility service](https://developer.android.com/tools/support-library/features.html#v4).

I wouldn't expect their to be a conflict between the android-support v4 and v13 libraries, but its worth checking, I suspect its something included in the older gcm helper library.  I cannot verify right now, but hopefully that gives you something to investigate.

A few comments:
- Its sorta bad practice to bundle a popular android lib directly with a plugin (like PushPlugin is doing), since in the long run it's going to cause duplication conflicts.  Instead, android libs should live in their own plugin which can be used as a shared dependency.
- Did you know we have a `chrome.gcm` plugin?  It only supports android, but works quite well.

**Comment by uriva** [comment]
Yeah I know about chrome.gcm, but I thought the whole point of this framework is that it is cross platform.

Some feedback to whom it may concern: for me the lack of cloud messaging for iOS, and the fact I can't easily use third party plugins to compensate for it, was the last straw... it takes a lot of effort trying to get things to work on iOS and android that it's just not worth it. Things appear easier within cordova.

Perhaps I'll try again when things are more mature.

**Comment by agrieve** [comment]
Closing since we can't really fix this on our end.

We do have a plugin for push messaging on iOS though: 
https://github.com/MobileChromeApps/mobile-chrome-apps/tree/master/chrome-cordova/plugins/chrome.pushMessaging

Likely the best setup for `cca` is to use chrome.gcm for Android, and chrome.pushMessaging for iOS.

**Comment by uriva** [comment]
1) Perhaps a better explanation about the project tree and a list of available plugins would be good in the main tutorial. I couldn't find this easily, although I did try searching something like this. Of course the name "mobile chrome apps" is very useless when searching.
2) It isn't clear from the docs of the chrome.pushMessaging if it enables display of notifications in iOS when the app is inactive. Also the docs refer the chrome API docs which state that this API is deprecated.

**Comment by mmocny** [comment]
@uriva which tutorial?  The one which starts at our [`README`](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/README.md)?

For a list of available plugins, you can see our [list of supported apis](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/docs/APIsAndLibraries.md).

chrome.PushMessaging is deprecated for desktop, you are correct, where Chrome Apps run in the Chrome Browser Runtime, because there is better support for chrome.gcm.  For Mobile, we have a created a cordova plugin that implements the same chrome apps api, but using a very different implementation (it uses iOS's `didReceiveRemoteNotification`).  So this plugin is not really affected by the desktop deprecation, except perhaps that we may not be quite as motivated to work on it in the future.

**Comment by uriva** [comment]
Now I see that the plugins are listed there, somehow missed that. Thanks.

However after reading about it, I still don't understand if the push messaging plugin enables display of notifications in iOS and android when the app is inactive (closed or inactive).
