### ISSUE TITLE
When using the argument --watch, I receive Operation not permitted.

### ISSUE THREAD

**Issue by topless** [MobileChromeApps/mobile-chrome-apps#511]
Whenever I am using `cca push --target=IP` on my Ubuntu 14.10 Gnome, I manage to successfully push my code to my device. If I pass the argument `--watch` the message in my console is `/bin/bash: line 0: ulimit: open files: cannot modify limit: Operation not permitted`. Both `ulimit -S && ulimit -H` are set to `unlimited`. Any ideas?

**Comment by mmocny** [comment]
The script itself tries to [adjust ulimit](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/src/push-to-harness.js#L197) since this is a common problem.  Perhaps there is a bug and we are overriding your manually set limits (assuming you set the limits yourself from shell before launching `cca run --watch`?)

**Comment by topless** [comment]
It doesn't work either when loads from `/etc/.../limits.conf`, or setting them manually, or load them from `.bashrc`. Could it be some sort of permission configuration on that particular machine?

**Comment by agrieve** [comment]
What does 'ulimit -n' output for you?

**Comment by topless** [comment]
`ulimit -n` now prints 8192 which is the value I define in `/etc/security/limits.conf`
