### ISSUE TITLE
window.open() should not use InAppBrowser

### ISSUE THREAD

**Issue by agrieve** [MobileChromeApps/mobile-chrome-apps#519]
When including chrome.identity, it pulls in InAppBrowser plugin. IAB clobbers window.open() with its own function. For Chrome Apps, we want the default behviour to always just open in external browser, and not IAB.

This somewhat trades one problem for another, since if someone *does* want to use IAB, then us reversing it's symbol mapping will prevent them from doing so. So, maybe we should instead do:

    window.iabOpen = window.open;
    delete window.open

Then at least there is an easy work-around. Note that this will have to be done in mobile.js's bgInit as well, since we map modules into both foreground and background windows.

Will also need to change chrome.identity to use IAB via require(), rather than window.open().

**Comment by sandstrom** [comment]
InAppBrowser is useful for authentication flows (OpenID-Connect, SAML, etc) in Cordova apps without needing custom protocols.

I understand the clobbering-issue (and I would actually prefer if this Cordova plugin didn't clobber `window.open`). Just wanted to chime in and say that I'd prefer if your solution leaves some way of accessing the iab-plugin.

I've opened an issue in Cordova's issue tracker on changing the api: 
https://issues.apache.org/jira/browse/CB-8444

**Comment by jpchase** [comment]
The Chrome Apps for Mobile framework has been changed to check for the InAppBrowser plugin, and undo the clobber for `window.open`.  This change does not copy/preserve the InAppBrowser implementation anywhere.  Instead, CB-8444 has been addressed to provide a uniquely-named API for InAppBrowser as `cordova.InAppBrowser.open`.  See the plugin docs for more details:
https://github.com/apache/cordova-plugin-inappbrowser

The fix for CB-8444 is not yet released.  Until then, the workaround is to explicitly require the InAppBrowser.  See the chrome.identity plugin as an example.
