### ISSUE TITLE
Differences config.xml and manifest.json

### ISSUE THREAD

**Issue by GustavoCostaW** [MobileChromeApps/mobile-chrome-apps#562]
I create new project for test and I check manifest.json and config.xml have icons to project, why?
this is a little confusing to me, what should I do with the manifest and what I should do with config.xml?
I know that the config.xml is a file to cordova project, and manifest is chrome app, but, why there is not just one? thx!

**Comment by schme16** [comment]
@GustavoCostaW: Just to remove any confusion, you only need to update the manifest.json file, when you run `cca prepare` the `cca` tool will make all necissary adjustments to the config.xml file for you.

As for the reason there are two, that's because all web apps are moving to using a manifest.json file (see: https://developer.chrome.com/extensions/manifest and https://w3c.github.io/manifest/); this helps keep your app consistent across multiple platforms; while cordova uses the config.xml format, so must be added for you; but as mentioned above, you do _not_ need to manually change the config.xml file, it will get updated when you run the `cca prepare` command.

**Comment by GustavoCostaW** [comment]
@schme16  thx!
