### ISSUE TITLE
Custom config.xml values get overwritten

### ISSUE THREAD

**Issue by darkoverlordofdata** [MobileChromeApps/mobile-chrome-apps#574]
I'm trying to set access origin to '*' for use with the cordova-plugin-whitelist. When I run cca build, the value is removed from config.xml
Some searching on the web leads to a reference that the value should be set in manifest.mobile.json.
So what do I set? I've tried adding:

  "access": {"origin": "*"}

But that does not do anything. Where can I find some doc on what to set for other config values? The mapping is not clear.

**Comment by schme16** [comment]
@darkoverlordofdata: Try adding this to your `manifest.json` file: 
```
"permissions": [
    "<all_urls>"
]
```

Reference: https://developer.chrome.com/extensions/match_patterns

**Comment by darkoverlordofdata** [comment]
No, it still removes my &lt;access origin="*" /&gt; tag. Close this - I'll wait and see if it actually denies access. Maybe it doesn't need it. I found this on https://github.com/apache/cordova-plugin-whitelist:

Without any <access> tags, only requests to file:// URLs are allowed. However, the default Cordova application includes <access origin="*"> by default.

Regarding the clobbering scheme - I see, that explains why the manifest.mobile.json author value overwrites the config.xml author tag text element, but doesn't touch the other attributes of the same tag. 
I'm just not real clear yet on which entries are custom and which are standard, but I'll know when they break ;)

**Comment by schme16** [comment]
@darkoverlordofdata: Are you sure it's not being removed because it's already added:
![2015-05-31 15_45_59-d__dropbox_www_games_burger-van_config xml burger-van - sublime text unregi](https://cloud.githubusercontent.com/assets/116081/7900761/4a1f51dc-07ac-11e5-8b4f-b71c69a3acaa.png)
Above is a screenshot from one of my config.xml files, with the great whopping line of hard to read attributes that are added by cca for us, but as you can see from the highlighting, the access origin attribute is present (just hard to spot).

**Comment by darkoverlordofdata** [comment]
Good call! That is exactly the case. I have the doc open in webstorm, so when I run build, I can watch the tag get removed. It's a long doc, and the tag is getting reinserted below the fold. When I scroll down, there it is. 

Thanks for your advice.
I appreciate now that cca is a smart tool ;)
